stages:
  Build:
    mavenExecuteStaticCodeChecks: false
    # npmExecuteLint: true

  Additional Unit Tests:
    npmExecuteScripts: false
    karmaExecuteTests: false

  # Acceptance:
  #   cloudFoundryDeploy: false
  #   cfApiEndpoint: "https://api.cf.eu10.hana.ondemand.com"
  #   cfOrg: "DBS Japan Shared_eu10"
  #   cfSpace: "demo-eu10"
  #   cfAppName: "dpedev"
  #   cfCredentialsId: "rasai-cf-deploy"
  #   uiVeri5ExecuteTests: false

  Release:
    cloudFoundryDeploy: true
    cfApiEndpoint: "https://api.cf.eu10.hana.ondemand.com"
    cfOrg: "DBS Japan Shared_eu10"
    cfSpace: "demo-eu10"
    cfAppName: "dpedev"
    cfCredentialsId: "rasai-cf-deploy"
    tmsUpload: true

steps:
  artifactPrepareVersion:
    versioningType: "cloud_noTag"

  # npmExecuteLint:
  #   failOnError: true

  cloudFoundryDeploy:
    mtaDeployParameters: "-f --version-rule ALL"

  tmsUpload:
    nodeName: "rasai-jp10-demo"
    credentialsId: "tms-rasai-sk"
    nodeExtDescriptorMapping:
      rasai-jp10-demo: 'qa.mtaext'
      rasai-jp10-demo1: 'prod.mtaext'